import type { BoardArrow, BoardNode } from './board-types';
import { isNodeInFrame } from './frames';
import type { Point } from './geometry';

export interface CanvasToD2Options {
  /**
   * Layout direction hint to place at the top of the D2 file.
   * 'auto': detects horizontal vs vertical bias based on canvas layout.
   * 'none': omits direction directive.
   * Defaults to 'auto'.
   */
  direction?: 'right' | 'down' | 'left' | 'up' | 'auto' | 'none';
  /** Whether to output color, stroke, and opacity styling. Defaults to true. */
  includeStyles?: boolean;
  /** Whether to nest elements contained inside frames into D2 containers. Defaults to true. */
  includeFrames?: boolean;
  /**
   * Optional list of node IDs to filter conversion to.
   * If provided and non-empty, only these nodes and arrows between them are exported.
   */
  selectedNodeIds?: string[];
  /** Whether to include a comment header. Defaults to false. */
  headerComment?: boolean;
}

const D2_RESERVED_KEYWORDS = new Set([
  'direction',
  'shape',
  'style',
  'icon',
  'label',
  'desc',
  'description',
  'tooltip',
  'link',
  'near',
  'width',
  'height',
  'top',
  'left',
  'class',
  'classes',
  'vars',
  'layers',
  'scenarios',
  'steps',
  'grid-rows',
  'grid-columns',
  'grid-gap',
  'horizontal',
  'vertical',
  'null',
]);

const TONE_FILL_MAP: Record<BoardNode['tone'], string> = {
  violet: '#ede8ff',
  orange: '#ffe0c8',
  blue: '#d9ebf8',
  yellow: '#fff0b8',
  mint: '#d4f5e9',
  note: '#fef3c7',
};

function escapeD2String(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r?\n/g, '\\n');
}

/**
 * Transforms a human label or ID into a clean, safe D2 identifier.
 */
export function sanitizeD2Identifier(label: string, fallback: string): string {
  const trimmed = label.trim();
  if (!trimmed) {
    return fallback;
  }

  // Remove leading 'd2:' prefix if from an imported D2 node
  const cleanLabel = trimmed.startsWith('d2:') ? trimmed.slice(3) : trimmed;

  let key = cleanLabel
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, '_')
    .replace(/^_+|_+$/g, '');

  if (!key || /^[0-9]/.test(key)) {
    key = `node_${key || fallback}`;
  }

  if (D2_RESERVED_KEYWORDS.has(key)) {
    key = `n_${key}`;
  }

  return key;
}

function findNodeAt(
  point: Point,
  nodes: BoardNode[],
  padding = 16,
): BoardNode | null {
  for (let i = nodes.length - 1; i >= 0; i--) {
    const node = nodes[i];
    if (node.shape === 'frame') continue;
    if (
      point.x >= node.x - padding &&
      point.x <= node.x + node.width + padding &&
      point.y >= node.y - padding &&
      point.y <= node.y + node.height + padding
    ) {
      return node;
    }
  }
  return null;
}

function mapShapeToD2(shape?: BoardNode['shape']): string | null {
  switch (shape) {
    case 'cylinder':
      return 'cylinder';
    case 'diamond':
      return 'diamond';
    case 'ellipse':
      return 'circle';
    case 'note':
      return 'note';
    case 'text':
      return 'text';
    case 'line':
      return 'line';
    case 'frame':
      return 'package';
    case 'round':
    default:
      return null; // D2 default is rectangle
  }
}

/**
 * Converts whiteboard nodes, frames, stencils, and arrows into clean D2 code.
 */
export function canvasToD2(
  nodes: BoardNode[],
  arrows: BoardArrow[],
  options: CanvasToD2Options = {},
): string {
  const {
    direction = 'auto',
    includeStyles = true,
    includeFrames = true,
    selectedNodeIds,
    headerComment = false,
  } = options;

  const filterSet =
    selectedNodeIds && selectedNodeIds.length > 0
      ? new Set(selectedNodeIds)
      : null;

  const candidateNodes = filterSet
    ? nodes.filter((n) => filterSet.has(n.id))
    : nodes;

  if (candidateNodes.length === 0) {
    return '';
  }

  const lines: string[] = [];

  if (headerComment) {
    lines.push('# Generated by Eunoia (Canvas-to-D2)');
  }

  // Determine direction
  if (direction !== 'none') {
    if (direction === 'auto') {
      let minX = Infinity;
      let maxX = -Infinity;
      let minY = Infinity;
      let maxY = -Infinity;

      for (const node of candidateNodes) {
        minX = Math.min(minX, node.x);
        maxX = Math.max(maxX, node.x + node.width);
        minY = Math.min(minY, node.y);
        maxY = Math.max(maxY, node.y + node.height);
      }

      const widthSpan = maxX - minX;
      const heightSpan = maxY - minY;

      if (widthSpan > heightSpan * 1.35) {
        lines.push('direction: right');
      } else if (heightSpan > widthSpan * 1.35) {
        lines.push('direction: down');
      }
    } else {
      lines.push(`direction: ${direction}`);
    }
  }

  if (lines.length > 0 && lines[lines.length - 1] !== '') {
    lines.push('');
  }

  // Separate frames and elements
  const allFrames = includeFrames
    ? candidateNodes.filter((n) => n.shape === 'frame')
    : [];
  const nonFrameNodes = candidateNodes.filter((n) => n.shape !== 'frame');

  // Sort frames so smallest area comes first (deepest container first)
  const sortedFrames = [...allFrames].sort(
    (a, b) => a.width * a.height - b.width * b.height,
  );

  // Map each node to its immediate parent frame
  const nodeParentFrame = new Map<string, BoardNode>();
  for (const node of nonFrameNodes) {
    for (const frame of sortedFrames) {
      if (isNodeInFrame(node, frame)) {
        nodeParentFrame.set(node.id, frame);
        break;
      }
    }
  }

  function isFrameInFrame(
    childFrame: BoardNode,
    parentFrame: BoardNode,
  ): boolean {
    if (childFrame.id === parentFrame.id) return false;
    if (
      childFrame.width * childFrame.height >=
      parentFrame.width * parentFrame.height
    ) {
      return false;
    }
    const cx = childFrame.x + childFrame.width / 2;
    const cy = childFrame.y + childFrame.height / 2;
    return (
      cx >= parentFrame.x &&
      cx <= parentFrame.x + parentFrame.width &&
      cy >= parentFrame.y &&
      cy <= parentFrame.y + parentFrame.height
    );
  }

  // Map frame to parent frame (nested frames)
  const frameParentFrame = new Map<string, BoardNode>();
  for (const childFrame of sortedFrames) {
    for (const parentFrame of sortedFrames) {
      if (isFrameInFrame(childFrame, parentFrame)) {
        frameParentFrame.set(childFrame.id, parentFrame);
        break;
      }
    }
  }

  // Assign unique keys to all candidate nodes and frames
  const seenKeys = new Set<string>();
  const nodeIdToKey = new Map<string, string>();

  function allocateKey(id: string, preferredLabel: string): string {
    const base = sanitizeD2Identifier(
      preferredLabel,
      `node_${seenKeys.size + 1}`,
    );
    let key = base;
    let counter = 2;
    while (seenKeys.has(key)) {
      key = `${base}_${counter}`;
      counter += 1;
    }
    seenKeys.add(key);
    nodeIdToKey.set(id, key);
    return key;
  }

  // Pre-allocate keys for frames first, then nodes
  for (const frame of sortedFrames) {
    allocateKey(frame.id, frame.label || 'container');
  }
  for (const node of nonFrameNodes) {
    allocateKey(node.id, node.label || 'node');
  }

  // Compute full scoped path (e.g., "vpc.sub_network.api")
  function getNodePath(nodeId: string): string {
    const localKey = nodeIdToKey.get(nodeId);
    if (!localKey) return 'unknown';

    let currentParent =
      nodeParentFrame.get(nodeId) || frameParentFrame.get(nodeId);
    const parentSegments: string[] = [];

    while (currentParent) {
      const parentKey = nodeIdToKey.get(currentParent.id);
      if (parentKey) {
        parentSegments.unshift(parentKey);
      }
      currentParent = frameParentFrame.get(currentParent.id);
    }

    if (parentSegments.length > 0) {
      return `${parentSegments.join('.')}.${localKey}`;
    }
    return localKey;
  }

  // Function to serialize a single non-frame node
  function serializeNode(node: BoardNode, indent: string): string[] {
    const key = nodeIdToKey.get(node.id)!;
    const shape = mapShapeToD2(node.shape);
    const label = node.label.trim();
    const hasProps =
      Boolean(shape) ||
      Boolean(node.icon) ||
      Boolean(node.detail?.trim()) ||
      Boolean(node.href) ||
      (includeStyles &&
        (Boolean(node.fill) ||
          Boolean(node.tone) ||
          Boolean(node.stroke) ||
          Boolean(node.dashed) ||
          (node.opacity !== undefined && node.opacity < 1)));

    const escapedLabel = escapeD2String(label || key);
    const nodeLines: string[] = [];

    if (!hasProps) {
      if (label && label !== key) {
        nodeLines.push(`${indent}${key}: "${escapedLabel}"`);
      } else {
        nodeLines.push(`${indent}${key}`);
      }
      return nodeLines;
    }

    // Node with block properties
    if (label && label !== key) {
      nodeLines.push(`${indent}${key}: "${escapedLabel}" {`);
    } else {
      nodeLines.push(`${indent}${key} {`);
    }

    const propIndent = `${indent}  `;

    if (shape) {
      nodeLines.push(`${propIndent}shape: ${shape}`);
    }

    if (node.icon) {
      nodeLines.push(`${propIndent}icon: "${escapeD2String(node.icon)}"`);
    }

    if (node.detail?.trim()) {
      nodeLines.push(
        `${propIndent}description: "${escapeD2String(node.detail.trim())}"`,
      );
    }

    if (node.href?.trim()) {
      nodeLines.push(
        `${propIndent}link: "${escapeD2String(node.href.trim())}"`,
      );
    }

    if (includeStyles) {
      const fill = node.fill || (node.tone && TONE_FILL_MAP[node.tone]);
      if (fill) {
        nodeLines.push(`${propIndent}style.fill: "${fill}"`);
      }
      if (node.stroke) {
        nodeLines.push(`${propIndent}style.stroke: "${node.stroke}"`);
      }
      if (node.strokeWidth && node.strokeWidth !== 2) {
        nodeLines.push(`${propIndent}style.stroke-width: ${node.strokeWidth}`);
      }
      if (node.dashed) {
        nodeLines.push(`${propIndent}style.stroke-dash: 3`);
      }
      if (node.opacity !== undefined && node.opacity < 1) {
        nodeLines.push(`${propIndent}style.opacity: ${node.opacity}`);
      }
    }

    nodeLines.push(`${indent}}`);
    return nodeLines;
  }

  // Recursive function to serialize frame and its children
  function serializeFrame(frame: BoardNode, indent: string): string[] {
    const key = nodeIdToKey.get(frame.id)!;
    const label = frame.label.trim();
    const escapedLabel = escapeD2String(label || key);
    const frameLines: string[] = [];

    if (label && label !== key) {
      frameLines.push(`${indent}${key}: "${escapedLabel}" {`);
    } else {
      frameLines.push(`${indent}${key} {`);
    }

    const childIndent = `${indent}  `;

    // Direct child frames
    const childFrames = sortedFrames.filter(
      (f) => frameParentFrame.get(f.id)?.id === frame.id,
    );
    for (const childFrame of childFrames) {
      frameLines.push(...serializeFrame(childFrame, childIndent));
    }

    // Direct child nodes
    const directChildNodes = nonFrameNodes.filter(
      (n) => nodeParentFrame.get(n.id)?.id === frame.id,
    );
    for (const childNode of directChildNodes) {
      frameLines.push(...serializeNode(childNode, childIndent));
    }

    frameLines.push(`${indent}}`);
    return frameLines;
  }

  // 1. Emit top-level frames
  const topLevelFrames = sortedFrames.filter(
    (f) => !frameParentFrame.has(f.id),
  );
  for (const frame of topLevelFrames) {
    lines.push(...serializeFrame(frame, ''));
    lines.push('');
  }

  // 2. Emit top-level nodes (not inside any frame)
  const topLevelNodes = nonFrameNodes.filter((n) => !nodeParentFrame.has(n.id));
  for (const node of topLevelNodes) {
    lines.push(...serializeNode(node, ''));
  }

  if (topLevelNodes.length > 0) {
    lines.push('');
  }

  // 3. Emit arrows / connections
  const renderedArrows: string[] = [];
  const knownNodes = candidateNodes;

  for (const arrow of arrows) {
    let startNodeId = arrow.startNodeId;
    let endNodeId = arrow.endNodeId;

    if (!startNodeId) {
      const hit = findNodeAt(arrow.start, knownNodes);
      if (hit) startNodeId = hit.id;
    }
    if (!endNodeId) {
      const hit = findNodeAt(arrow.end, knownNodes);
      if (hit) endNodeId = hit.id;
    }

    if (!startNodeId || !endNodeId) continue;
    if (startNodeId === endNodeId) continue;

    // Both must be part of candidate nodes
    if (!nodeIdToKey.has(startNodeId) || !nodeIdToKey.has(endNodeId)) continue;

    const fromPath = getNodePath(startNodeId);
    const toPath = getNodePath(endNodeId);

    const hasArrowProps =
      includeStyles && Boolean(arrow.color && arrow.color !== '#6b7192');

    if (hasArrowProps) {
      renderedArrows.push(`${fromPath} -> ${toPath} {`);
      renderedArrows.push(`  style.stroke: "${arrow.color}"`);
      renderedArrows.push('}');
    } else {
      renderedArrows.push(`${fromPath} -> ${toPath}`);
    }
  }

  if (renderedArrows.length > 0) {
    if (lines.length > 0 && lines[lines.length - 1] !== '') {
      lines.push('');
    }
    lines.push('# Connections');
    lines.push(...renderedArrows);
  }

  // Filter trailing empty lines and join
  while (lines.length > 0 && lines[lines.length - 1] === '') {
    lines.pop();
  }

  return lines.join('\n') + '\n';
}
